# Generated by Django 5.2.6 on 2025-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('recruiter', 'Recruiter')], default='freelancer', max_length=20),
        ),
    ]
