# Generated by Django 5.2.6 on 2025-09-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginattempt_alter_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginattempt',
            old_name='successful',
            new_name='success',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
