# Generated by Django 5.2.6 on 2025-09-25 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_rename_successful_loginattempt_success_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer_detail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
