<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-15 21:50
=======
# Generated by Django 5.2.6 on 2025-10-08 13:10
>>>>>>> origin/main

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer_detail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
<<<<<<< HEAD
                ('mobile_No', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('bio', models.TextField(blank=True, null=True)),
                ('ge', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('sample_work', models.FileField(blank=True, null=True, upload_to='sample_works/')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lambdainkedin_profile', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
=======
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
>>>>>>> origin/main
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('Github', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('courseName', models.TextField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('completionDate', models.DateField(blank=True, null=True)),
                ('jobpreferences', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
            ],
        ),
    ]
