# Generated by Django 5.2.6 on 2025-10-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_detail',
            name='jobpreferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer_detail',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
