# Generated by Django 5.2.6 on 2025-09-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='email',
        ),
    ]
