# Generated by Django 5.2.6 on 2025-09-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0002_remove_freelancer_detail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='name',
        ),
    ]
