# Generated by Django 5.2.6 on 2025-10-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0002_alter_freelancer_detail_jobpreferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='completionDate',
        ),
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='university',
        ),
    ]
