# Generated by Django 5.2.6 on 2025-10-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0003_remove_freelancer_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='age',
        ),
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='skills',
        ),
    ]
