# Generated by Django 5.2.6 on 2025-10-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0003_remove_freelancer_detail_completiondate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer_detail',
            old_name='Github',
            new_name='github',
        ),
    ]
