# Generated by Django 5.2.6 on 2025-10-04 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0003_remove_freelancer_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer_detail',
            name='age',
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='Github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='Linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='Mobile_No',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='sample_work',
            field=models.FileField(blank=True, null=True, upload_to='sample_works/'),
        ),
        migrations.AddField(
            model_name='freelancer_detail',
            name='Age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
