# Generated by Django 5.2.6 on 2025-10-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0004_remove_freelancer_detail_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer_detail',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='freelancer_detail',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='freelancer_detail',
            old_name='Age',
            new_name='ge',
        ),
        migrations.RenameField(
            model_name='freelancer_detail',
            old_name='Github_profile',
            new_name='github_profile',
        ),
        migrations.RenameField(
            model_name='freelancer_detail',
            old_name='Linkedin_profile',
            new_name='lambdainkedin_profile',
        ),
        migrations.RenameField(
            model_name='freelancer_detail',
            old_name='Mobile_No',
            new_name='mobile_No',
        ),
    ]
