# Generated by Django 5.2.6 on 2025-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recruiter_name', models.CharField(max_length=100)),
                ('Organisation', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
            ],
        ),
    ]
