# Generated by Django 5.2.6 on 2025-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter_detail',
            name='job_title',
        ),
        migrations.AddField(
            model_name='recruiter_detail',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter_detail',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
