# Generated by Django 5.2.6 on 2025-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter_detail',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter_detail',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
