# Generated by Django 5.2.6 on 2025-10-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter_detail',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='recruiter_detail',
            name='job_title',
        ),
    ]
