# Generated by Django 5.2.6 on 2025-10-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='id',
            new_name='job_id',
        ),
    ]
